/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'admin' : null } |
  { 'employer' : null } |
  { 'candidate' : null };
export interface Application {
  'id' : bigint,
  'status' : ApplicationStatusType,
  'appliedAt' : bigint,
  'jobId' : bigint,
  'candidateId' : Principal,
}
export type ApplicationStatusType = { 'hired' : null } |
  { 'interview' : null } |
  { 'applied' : null } |
  { 'rejected' : null } |
  { 'shortlisted' : null };
export interface CandidateProfile {
  'resume' : [] | [string],
  'userId' : Principal,
  'name' : string,
  'email' : string,
  'experience' : string,
  'skills' : Array<string>,
}
export interface CandidateProfileInput {
  'resume' : [] | [string],
  'name' : string,
  'email' : string,
  'experience' : string,
  'skills' : Array<string>,
}
export interface EmployerProfile {
  'userId' : Principal,
  'companyLocation' : string,
  'email' : string,
  'companyName' : string,
  'companyDescription' : string,
}
export interface EmployerProfileInput {
  'companyLocation' : string,
  'email' : string,
  'companyName' : string,
  'companyDescription' : string,
}
export interface JobFilters {
  'status' : [] | [JobStatus],
  'jobType' : [] | [JobType],
  'keyword' : [] | [string],
  'salaryRange' : [] | [[bigint, bigint]],
  'location' : [] | [string],
}
export interface JobInput {
  'status' : JobStatus,
  'title' : string,
  'salary' : bigint,
  'jobType' : JobType,
  'slug' : string,
  'description' : string,
  'location' : string,
}
export interface JobPosting {
  'id' : bigint,
  'status' : JobStatus,
  'title' : string,
  'created' : bigint,
  'modified' : bigint,
  'salary' : bigint,
  'jobType' : JobType,
  'slug' : string,
  'description' : string,
  'employerId' : Principal,
  'location' : string,
}
export type JobStatus = { 'closed' : null } |
  { 'published' : null } |
  { 'draft' : null };
export type JobType = { 'contract' : null } |
  { 'partTime' : null } |
  { 'fullTime' : null } |
  { 'freelance' : null };
export interface UserProfile {
  'appRole' : AppRole,
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyForJob' : ActorMethod<[bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteJob' : ActorMethod<[bigint], undefined>,
  'getApplication' : ActorMethod<[bigint], [] | [Application]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandidateProfile' : ActorMethod<[Principal], [] | [CandidateProfile]>,
  'getEmployerProfile' : ActorMethod<[Principal], [] | [EmployerProfile]>,
  'getJob' : ActorMethod<[bigint], [] | [JobPosting]>,
  'getJobBySlug' : ActorMethod<[string], [] | [JobPosting]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllApplications' : ActorMethod<[], Array<Application>>,
  'listAllCandidates' : ActorMethod<[], Array<CandidateProfile>>,
  'listAllEmployers' : ActorMethod<[], Array<EmployerProfile>>,
  'listAllJobs' : ActorMethod<[], Array<JobPosting>>,
  'listCandidateApplications' : ActorMethod<[Principal], Array<Application>>,
  'listFilteredJobs' : ActorMethod<[JobFilters], Array<JobPosting>>,
  'listJobApplications' : ActorMethod<[bigint], Array<Application>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCandidateProfile' : ActorMethod<[CandidateProfileInput], undefined>,
  'saveEmployerProfile' : ActorMethod<[EmployerProfileInput], undefined>,
  'saveJob' : ActorMethod<[JobInput], bigint>,
  'updateApplicationStatus' : ActorMethod<
    [bigint, ApplicationStatusType],
    undefined
  >,
  'updateJob' : ActorMethod<[bigint, JobInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];