/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApplicationStatusType = IDL.Variant({
  'hired' : IDL.Null,
  'interview' : IDL.Null,
  'applied' : IDL.Null,
  'rejected' : IDL.Null,
  'shortlisted' : IDL.Null,
});
export const Application = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatusType,
  'appliedAt' : IDL.Int,
  'jobId' : IDL.Nat,
  'candidateId' : IDL.Principal,
});
export const AppRole = IDL.Variant({
  'admin' : IDL.Null,
  'employer' : IDL.Null,
  'candidate' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'appRole' : AppRole,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const CandidateProfile = IDL.Record({
  'resume' : IDL.Opt(IDL.Text),
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'experience' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});
export const EmployerProfile = IDL.Record({
  'userId' : IDL.Principal,
  'companyLocation' : IDL.Text,
  'email' : IDL.Text,
  'companyName' : IDL.Text,
  'companyDescription' : IDL.Text,
});
export const JobStatus = IDL.Variant({
  'closed' : IDL.Null,
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const JobType = IDL.Variant({
  'contract' : IDL.Null,
  'partTime' : IDL.Null,
  'fullTime' : IDL.Null,
  'freelance' : IDL.Null,
});
export const JobPosting = IDL.Record({
  'id' : IDL.Nat,
  'status' : JobStatus,
  'title' : IDL.Text,
  'created' : IDL.Int,
  'modified' : IDL.Int,
  'salary' : IDL.Nat,
  'jobType' : JobType,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'employerId' : IDL.Principal,
  'location' : IDL.Text,
});
export const JobFilters = IDL.Record({
  'status' : IDL.Opt(JobStatus),
  'jobType' : IDL.Opt(JobType),
  'keyword' : IDL.Opt(IDL.Text),
  'salaryRange' : IDL.Opt(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'location' : IDL.Opt(IDL.Text),
});
export const CandidateProfileInput = IDL.Record({
  'resume' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'experience' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});
export const EmployerProfileInput = IDL.Record({
  'companyLocation' : IDL.Text,
  'email' : IDL.Text,
  'companyName' : IDL.Text,
  'companyDescription' : IDL.Text,
});
export const JobInput = IDL.Record({
  'status' : JobStatus,
  'title' : IDL.Text,
  'salary' : IDL.Nat,
  'jobType' : JobType,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyForJob' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteJob' : IDL.Func([IDL.Nat], [], []),
  'getApplication' : IDL.Func([IDL.Nat], [IDL.Opt(Application)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandidateProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CandidateProfile)],
      ['query'],
    ),
  'getEmployerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(EmployerProfile)],
      ['query'],
    ),
  'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(JobPosting)], ['query']),
  'getJobBySlug' : IDL.Func([IDL.Text], [IDL.Opt(JobPosting)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'listAllCandidates' : IDL.Func([], [IDL.Vec(CandidateProfile)], ['query']),
  'listAllEmployers' : IDL.Func([], [IDL.Vec(EmployerProfile)], ['query']),
  'listAllJobs' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'listCandidateApplications' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Application)],
      ['query'],
    ),
  'listFilteredJobs' : IDL.Func([JobFilters], [IDL.Vec(JobPosting)], ['query']),
  'listJobApplications' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Application)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCandidateProfile' : IDL.Func([CandidateProfileInput], [], []),
  'saveEmployerProfile' : IDL.Func([EmployerProfileInput], [], []),
  'saveJob' : IDL.Func([JobInput], [IDL.Nat], []),
  'updateApplicationStatus' : IDL.Func(
      [IDL.Nat, ApplicationStatusType],
      [],
      [],
    ),
  'updateJob' : IDL.Func([IDL.Nat, JobInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApplicationStatusType = IDL.Variant({
    'hired' : IDL.Null,
    'interview' : IDL.Null,
    'applied' : IDL.Null,
    'rejected' : IDL.Null,
    'shortlisted' : IDL.Null,
  });
  const Application = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatusType,
    'appliedAt' : IDL.Int,
    'jobId' : IDL.Nat,
    'candidateId' : IDL.Principal,
  });
  const AppRole = IDL.Variant({
    'admin' : IDL.Null,
    'employer' : IDL.Null,
    'candidate' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'appRole' : AppRole,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const CandidateProfile = IDL.Record({
    'resume' : IDL.Opt(IDL.Text),
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'experience' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  const EmployerProfile = IDL.Record({
    'userId' : IDL.Principal,
    'companyLocation' : IDL.Text,
    'email' : IDL.Text,
    'companyName' : IDL.Text,
    'companyDescription' : IDL.Text,
  });
  const JobStatus = IDL.Variant({
    'closed' : IDL.Null,
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const JobType = IDL.Variant({
    'contract' : IDL.Null,
    'partTime' : IDL.Null,
    'fullTime' : IDL.Null,
    'freelance' : IDL.Null,
  });
  const JobPosting = IDL.Record({
    'id' : IDL.Nat,
    'status' : JobStatus,
    'title' : IDL.Text,
    'created' : IDL.Int,
    'modified' : IDL.Int,
    'salary' : IDL.Nat,
    'jobType' : JobType,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'employerId' : IDL.Principal,
    'location' : IDL.Text,
  });
  const JobFilters = IDL.Record({
    'status' : IDL.Opt(JobStatus),
    'jobType' : IDL.Opt(JobType),
    'keyword' : IDL.Opt(IDL.Text),
    'salaryRange' : IDL.Opt(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'location' : IDL.Opt(IDL.Text),
  });
  const CandidateProfileInput = IDL.Record({
    'resume' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'experience' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  const EmployerProfileInput = IDL.Record({
    'companyLocation' : IDL.Text,
    'email' : IDL.Text,
    'companyName' : IDL.Text,
    'companyDescription' : IDL.Text,
  });
  const JobInput = IDL.Record({
    'status' : JobStatus,
    'title' : IDL.Text,
    'salary' : IDL.Nat,
    'jobType' : JobType,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyForJob' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteJob' : IDL.Func([IDL.Nat], [], []),
    'getApplication' : IDL.Func([IDL.Nat], [IDL.Opt(Application)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandidateProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CandidateProfile)],
        ['query'],
      ),
    'getEmployerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(EmployerProfile)],
        ['query'],
      ),
    'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(JobPosting)], ['query']),
    'getJobBySlug' : IDL.Func([IDL.Text], [IDL.Opt(JobPosting)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'listAllCandidates' : IDL.Func([], [IDL.Vec(CandidateProfile)], ['query']),
    'listAllEmployers' : IDL.Func([], [IDL.Vec(EmployerProfile)], ['query']),
    'listAllJobs' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'listCandidateApplications' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'listFilteredJobs' : IDL.Func(
        [JobFilters],
        [IDL.Vec(JobPosting)],
        ['query'],
      ),
    'listJobApplications' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCandidateProfile' : IDL.Func([CandidateProfileInput], [], []),
    'saveEmployerProfile' : IDL.Func([EmployerProfileInput], [], []),
    'saveJob' : IDL.Func([JobInput], [IDL.Nat], []),
    'updateApplicationStatus' : IDL.Func(
        [IDL.Nat, ApplicationStatusType],
        [],
        [],
      ),
    'updateJob' : IDL.Func([IDL.Nat, JobInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };